### ISSUE TITLE
Q: What is the preferred way to use adifferent github api?

### ISSUE THREAD

**Issue by keithmantell** [Raynes/tentacles#101]
for instance if I want to use e.g. https://api.github.xyz.com/  is this the correct/preferred method?

`(binding [tentacles.core/url "https://api.github.xyz.com/"] (pp/pprint (users/me )))`

**Comment by functor-soup** [comment]
@keithmantell look at the macro `with-url` in `core.clj`  ( Pr #11) ..all in all your code snippet is right, but there already exists a macro within the library that odes the same. Hope that answers your question.
