### ISSUE TITLE
Publish the new version to Clojars

### ISSUE THREAD

**Issue by agilecreativity** [Raynes/tentacles#107]
Hi @Raynes,

Would you be kind enough to publish the new version to Clojars so we can use the new update in the `project.clj`.

Currently the last publish version was at [0.5.1](https://clojars.org/tentacles).
Thanks again for your great contribution.

**Comment by pmonks** [comment]
I'm using [Jitpack.io](https://jitpack.io/#raynes/tentacles) as a workaround in the meantime.  It's pretty awesome!

**Comment by agilecreativity** [comment]
@pmonks Thanks for the tips. Will give this a try.

**Comment by jjl** [comment]
Hello,

We now maintain a fork of tentacles which is published to clojars at [irresponsible/tentacles](https://github.com/irresponsible/tentacles).

Raynes unfortunately passed away, but we will try and keep his legacy alive. A v0.6.0 has been uploaded to clojars as 'irresponsible/tentacles'.

Please find more details in this post:
https://groups.google.com/forum/#!topic/clojure/UJetyHj-BPE
