### ISSUE TITLE
releases api

### ISSUE THREAD

**Issue by wilkerlucio** [Raynes/tentacles#59]
Hi,

Do you plan to support the releases API? I couldn't find the functions for it here: https://developer.github.com/v3/repos/releases/

Thanks.

**Comment by joelittlejohn** [comment]
Looks like this one can be closed:

See dba4f5b3dcacffab37b0bf8fd43ae7a93add3fc3 and https://github.com/Raynes/tentacles/blob/0122d739aa04c37977817868202877de84c67142/src/tentacles/repos.clj#L550.
