### ISSUE TITLE
Support updating a file

### ISSUE THREAD

**Issue by johnkelly** [Raynes/tentacles#77]
Maybe I'm missing something (new to Clojure), but I don't think the update file api is included currently: https://developer.github.com/v3/repos/contents/#update-a-file.

**Comment by shmish111** [comment]
I was just going to raise this same issue, I will see if I have time to look into the code anyway

**Comment by Raynes** [comment]
I'm not really actively maintaining this project at the moment as much as accepting pull requests and trying to keep releases moving when needed.

**Comment by shmish111** [comment]
I've added https://github.com/Raynes/tentacles/pull/78

**Comment by shmish111** [comment]
bump ;-)

**Comment by Raynes** [comment]
http://i0.kym-cdn.com/photos/images/facebook/000/140/023/1308937549001.jpg

**Comment by shmish111** [comment]
:+1: and is a release possible?

**Comment by Raynes** [comment]
Utterly unheard of.

**Comment by shmish111** [comment]
http://a38898d4011a160a051fb191.gearheads.netdna-cdn.com/wp-content/uploads/2012/10/omg-omg-moments-28947388-800-554.jpg?e1be4f

**Comment by Raynes** [comment]
Released 0.4.0.
