### ISSUE TITLE
defaults are not added to request headers

### ISSUE THREAD

**Issue by joelittlejohn** [Raynes/tentacles#85]
Hi @Raynes, loving your work :smiley: I've been having a problem writing to the GitHub API and I think it's caused by my defaults not being added to the request correctly.

In [`tentacles.core/make-request`](https://github.com/Raynes/tentacles/blob/0122d739aa04c37977817868202877de84c67142/src/tentacles/core.clj#L86) we build up a request, adding headers if necessary. _After_ adding headers, the defaults are merged into the query map. This process means that defaults can appear in a request body (for put/post/delete) or in the query string (for get etc), but they cannot go into headers.

I'm trying to use GitHub Trees API and I'm finding that the `:oauth-token` value I have in my tentacles defaults is ignored. It appears to be because this API does not allow the token to be supplied in the body, it _has_ to be in the Authorization header.

I think we should merge defaults in _before_ deciding which headers to add. Does this sound sensible? If so I'm happy to submit a PR for this.

**Comment by Raynes** [comment]
You're probably more familiar with this code at this point than I am. If you write it, test it, and it works I'll definitely merge it.

**Comment by joelittlejohn** [comment]
@Raynes thanks! I've pushed #86 to sort this out.
