### ISSUE TITLE
Tentacles broken with Clojure 1.8.0

### ISSUE THREAD

**Issue by wkf** [Raynes/tentacles#89]
Hey there, I'm running into an issue trying to use tentacles with clojure `1.8.0`.

I get the following error when requiring the `tentacles.pulls` namespace:

```
CompilerException java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap, compiling:(clj_http/headers.clj:105:1) 
```

Thanks for the sweet tool.

**Comment by iamjarvo** [comment]
Experiencing this also. I think I have a fix, will open a pr in a bit.

**Comment by gumatias** [comment]
Having the same issue

**Comment by ricardojmendez** [comment]
I have just cloned the repository, upgraded the dependencies and Clojure, and do not get this issue. I am able to query pull requests just fine. 

Maybe it also requires upgrading clj-http.

**Comment by Raynes** [comment]
This is fixed in master I believe.

**Comment by devurandom** [comment]
Would it be possible to release an updated version containing this fix? I just ran into it, too.

**Comment by iamjarvo** [comment]
@devurandom I'll see if I am able to get a new version published to clojars but in the meantime you can use https://github.com/Raynes/tentacles/issues/107#issuecomment-259311501 as a work around
